[project]
name = "rag-search-engine"
version = "0.1.0"
description = "A RAG search engine for movies"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nltk>=3.9.2",
    "numpy>=2.3.4",
    "sentence-transformers>=5.1.1",
]
